apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  MYSQL_HOST: <base64-encoded-rds-endpoint>
  MYSQL_USER: <base64-encoded-db-username>
  MYSQL_PASSWORD: <base64-encoded-db-password>
  MYSQL_DATABASE: <base64-encoded-database-name>
